#ifndef DEFS_H_INCLUDED
#define DEFS_H_INCLUDED
    float prob1(char * sourceIPs, char *sourceIP, int len);
    float sourceIPsEntropy(char *sourceIPs,int len);
    int isWindow (double t0, double t1, double windowLength);
    float sourceIPsVariation(char *sourceIPs);
    void preProcessing();
    typedef struct {
    int frame_interface_id;
    char 	     frame_dlt[1];
    char 	frame_offset_shift[1];
    char 	frame_time_epoch[16];
    char 	frame_time_delta[1];
    char 	frame_time_delta_displayed[1];
    char 	frame_time_relative[1];
    char  	frame_len[1];
    char  	frame_cap_len[1];
    char 	frame_marked[1]	;
    char 	frame_ignored[1]	;
    char 	radiotap_version[1]	;
    char 	radiotap_pad[1]	;
    char 	radiotap_length[1]	;//parei
    char 	radiotap_present_tsft[1]	;
    char 	radiotap_present_flags[1]	;
    char 	radiotap_present_rate[1]	;
    char 	radiotap_present_channel[1]	;
    char 	radiotap_present_fhss[1]	;
    char 	radiotap_present_dbm_antsignal[1]	;
    char 	radiotap_present_dbm_antnoise[1]	;
    char 	radiotap_present_lock_quality[1]	;
    char 	radiotap_present_tx_attenuation[1]	;
    char 	radiotap_present_db_tx_attenuation[1]	;
    char 	radiotap_present_dbm_tx_power[1]	;
    char 	radiotap_present_antenna[1]	;
    char 	radiotap_present_db_antsignal[1]	;
    char 	radiotap_present_db_antnoise[1]	;
    char 	radiotap_present_rxflags[1]	;
    char 	radiotap_present_xchannel[1]	;
    char 	radiotap_present_mcs[1]	;
    char 	radiotap_present_ampdu[1]	;
    char 	radiotap_present_vht[1]	;
    char	radiotap_present_reserved[1]	;
    char 	radiotap_present_rtap_ns[1]	;
    char 	radiotap_present_vendor_ns[1]	;
    char 	radiotap_present_ext[1]	;
    char 	radiotap_mactime[1]	;
    char 	radiotap_flags_cfp[1]	;
    char 	radiotap_flags_preamble[1]	;
    char 	radiotap_flags_wep[1]	;
    char 	radiotap_flags_frag[1]	;
    char 	radiotap_flags_fcs[1]	;
    char 	radiotap_flags_datapad[1]	;
    char 	radiotap_flags_badfcs[1]	;
    char 	radiotap_flags_shortgi[1]	;
    char 	radiotap_datarate[1]	;
    char  	radiotap_channel_freq[1]	;
    char 	radiotap_channel_type_turbo[1]	;
    char 	radiotap_channel_type_cck[1]	;
    char 	radiotap_channel_type_ofdm[1]	;
    char 	radiotap_channel_type_2ghz[1]	;
    char 	radiotap_channel_type_5ghz[1]	;
    char 	radiotap_channel_type_passive[1]	;
    char 	radiotap_channel_type_dynamic[1]	;
    char 	radiotap_channel_type_gfsk[1]	;
    char 	radiotap_channel_type_gsm[1]	;
    char 	radiotap_channel_type_sturbo[1]	;
    char 	radiotap_channel_type_half[1]	;
    char 	radiotap_channel_type_quarter[1]	;
    char 	radiotap_dbm_antsignal[1]	;
    char 	radiotap_antenna[1]	;
    char 	radiotap_rxflags_badplcp[1]	;
    char 	wlan_fc_type_subtype[1]	;
    char 	wlan_fc_version	[1];
    char 	wlan_fc_type[1]	;
    char 	wlan_fc_subtype[1]	;
    char 	wlan_fc_ds[1]	;
    char 	wlan_fc_frag[1]	;
    char 	wlan_fc_retry[1]	;
    char 	wlan_fc_pwrmgt[1]	;
    char 	wlan_fc_moredata[1]	;
    char 	wlan_fc_protected[1]	;
    char 	wlan_fc_order[1]	;
    char 	wlan_duration[1]	;
    char 	wlan_ra[18]	;//Receiver address	(Ethernet or other MAC address)
    char	wlan_da[18] 	; //Destination address (Ethernet or other MAC address)
    char 	wlan_ta[18]	; // Transmitter address (Ethernet or other MAC address)
    char 	wlan_sa[18]	;// Source address ((Ethernet or other MAC address))
    char 	wlan_bssid[18]	; //	BSS Id
    char 	wlan_frag[1]	;
    char 	wlan_seq[1]	;
    char 	wlan_bar_type[1]	;
    char 	wlan_ba_control_ackpolicy[1]	;
    char 	wlan_ba_control_multitid[1]	;
    char 	wlan_ba_control_cbitmap[1]	;
    char  	wlan_bar_compressed_tidinfo[1]	;
    char  	wlan_ba_bm[1]	;
    char 	wlan_fcs_good[1]	;
    char 	wlan_mgt_fixed_capabilities_ess[1]	;
    char 	wlan_mgt_fixed_capabilities_ibss[1]	;
    char    wlan_mgt_fixed_capabilities_cfpoll_ap[1]	;
    char 	wlan_mgt_fixed_capabilities_privacy[1]	;
    char 	wlan_mgt_fixed_capabilities_preamble[1]	;
    char 	wlan_mgt_fixed_capabilities_pbcc[1]	;
    char 	wlan_mgt_fixed_capabilities_agility	[1];
    char 	wlan_mgt_fixed_capabilities_spec_man[1]	;
    char 	wlan_mgt_fixed_capabilities_short_slot_time	[1];
    char 	wlan_mgt_fixed_capabilities_apsd[1]	;
    char 	wlan_mgt_fixed_capabilities_radio_measurement[1]	;
    char 	wlan_mgt_fixed_capabilities_dsss_ofdm[1]	;
    char 	wlan_mgt_fixed_capabilities_del_blk_ack[1]	;
    char 	wlan_mgt_fixed_capabilities_imm_blk_ack	[1];
    char  	wlan_mgt_fixed_listen_ival[1]	;
    char 	wlan_mgt_fixed_current_ap[1]	; // Current AP(Ethernet or MAC addres)
    char    wlan_mgt_fixed_status_code[1]	;
    char 	wlan_mgt_fixed_timestamp[1]	;
    char 	wlan_mgt_fixed_beacon[1]	;
    char  	wlan_mgt_fixed_aid[1]	;
    char 	wlan_mgt_fixed_reason_code[1]	;
    char 	wlan_mgt_fixed_auth_alg[1]	;
    char 	wlan_mgt_fixed_auth_seq	[1];
    char 	wlan_mgt_fixed_category_code[1]	;
    char 	wlan_mgt_fixed_htact[1]	;
    char 	wlan_mgt_fixed_chanwidth[1]	;
    char 	wlan_mgt_fixed_fragment[1]	;
    char  	wlan_mgt_fixed_sequence	[1];
    char	wlan_mgt_tagged_all[1] 	;
    char 	wlan_mgt_ssid[1]	;
    char 	wlan_mgt_ds_current_channel[1]	;
    char 	wlan_mgt_tim_dtim_count[1]	;
    char 	wlan_mgt_tim_dtim_period[1]	;
    char 	wlan_mgt_tim_bmapctl_multicast[1]	;
    char 	wlan_mgt_tim_bmapctl_offset[1]	;
    char 	wlan_mgt_country_info_environment[1]	;
    char  	wlan_mgt_rsn_version[1]	;
    char 	wlan_mgt_rsn_gcs_type[1]	;
    char 	wlan_mgt_rsn_pcs_count[1]	;
    char 	wlan_mgt_rsn_akms_count[1]	;
    char 	wlan_mgt_rsn_akms_type[1]	;
    char 	wlan_mgt_rsn_capabilities_preauth[1]	;
    char 	wlan_mgt_rsn_capabilities_no_pairwise[1]	;
    char 	wlan_mgt_rsn_capabilities_ptksa_replay_counter[1]	;
    char 	wlan_mgt_rsn_capabilities_gtksa_replay_counter[1]	;
    char 	wlan_mgt_rsn_capabilities_mfpr[1]	;
    char 	wlan_mgt_rsn_capabilities_mfpc[1]	;
    char 	wlan_mgt_rsn_capabilities_peerkey[1]	;
    char 	wlan_mgt_tcprep_trsmt_pow[1]	;
    char 	wlan_mgt_tcprep_link_mrg[1]	;
    char 	wlan_wep_iv[8]	;
    char 	wlan_wep_key[1]	;
    char 	wlan_wep_icv[1]	;
    char 	wlan_tkip_extiv[1]	;
    char 	wlan_ccmp_extiv[1]	;
    char 	wlan_qos_tid[1]	;
    char 	wlan_qos_priority[1]	;
    char 	wlan_qos_eosp[1]	;
    char 	wlan_qos_ack[6]	;
    char 	wlan_qos_amsdupresent[1]	;
    char 	wlan_qos_buf_state_indicated0[1]	;
    char 	a[1]	;
    char 	wlan_qos_txop_dur_req[1]	;
    char 	wlan_qos_buf_state_indicated1[1]	;
    char 	data_len[1]	;
    char 	classification[6]	;
    }Awid;




#endif // DEFS_H_INCLUDED
